version: '3.1'

services:

  db:
    # database with mariadb
    image: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=mattermost
      - MYSQL_USER=mattermost
      - MYSQL_PASSWORD=mattermost
      - PROXY=${http_proxy}
    volumes:
       - ./volumes/db/var/lib/mariadb/data:/var/lib/mysql
       - ./volumes/srv:/srv
       - /etc/localtime:/etc/localtime:ro
    expose:
      - 3306

  app:
    build:
      context: app
      args:
        - edition=team
        - PUID=${UID}
        - PGID=${GID}

    depends_on: 
    - db
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - ./volumes/srv:/srv
      - /etc/localtime:/etc/localtime:ro
    ports:
     - "8040:8000"
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=mattermost
      - MM_PASSWORD=mattermost
      - MM_DBNAME=mattermost
      - DB_HOST=db
      - DB_PORT_NUMBER=3306
      - MM_SQLSETTINGS_DRIVERNAME=mysql
      - MM_SQLSETTINGS_DATASOURCE=mattermost:mattermost@tcp(db:3306)/mattermost?charset=utf8mb4,utf8

